#!/usr/bin/env python3
"""
Regenerate every app icon from the logo component, and check the mark has not
drifted between the three apps.

The icon and the in-app wordmark are the same mark; the only way to keep them
that way through a redesign is to build one from the other. Run this after any
change to components/logo.tsx:

    python3 scripts/build-icons.py

The marketplace, the partner console and the business console each ship their
own copy of the component — they are separate Next apps and `@ciao/shared` is
consumed by the API too, so it cannot hold JSX. Three copies of a logo is
exactly how a brand ends up with three logos, so this script fails loudly if
they stop being byte-identical rather than waiting for someone to notice a
different mark on partners.ciao.ly.

It now generates the partner and console icons too, which it previously did
not. That gap is why those two apps were still shipping the retired Greeting
Bubble on their home screens a redesign later: nothing regenerated them, and
nothing complained. An asset that has to be remembered is an asset that goes
stale.
"""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

CANONICAL = ROOT / "apps/web/src/components/logo.tsx"
COPIES = [
    ROOT / "apps/partner/src/components/logo.tsx",
    ROOT / "apps/console/src/components/logo.tsx",
]
comp = CANONICAL.read_text()
drifted = [p for p in COPIES if p.read_text() != comp]
if drifted:
    for p in drifted:
        print(f"logo drift: {p.relative_to(ROOT)} differs from apps/web", file=sys.stderr)
    print("copy the marketplace component over them and re-run.", file=sys.stderr)
    raise SystemExit(1)

WORD = re.search(r'const WORD_PATH =\n  "(.+?)";', comp, re.S).group(1)
STOP = re.search(r'const STOP_PATH =\n  "(.+?)";', comp, re.S).group(1)
# Tight to the ink, matching the component. Padding below belongs to the icon,
# not to the artwork, which is why it is computed here rather than baked in.
VB_W, VB_H = 225.35, 100.0

NAVY, CREAM, GOLD = "#0d1b2a", "#f5eedd", "#e8a020"

# One family, three unmistakable members.
#
# The operator who runs the company plausibly has all three on one phone, and a
# partner and a guest very often will. Two icons differing only in a shade are
# two icons somebody opens the wrong one of at seven in the morning. So the
# ground changes completely between them while the mark does not change at all
# — the same trick the wordmark plays between light and dark.
#
# The stop keeps its rule throughout: it is the one element allowed to change
# colour, and it changes only where it would otherwise vanish into its own
# ground, which is the business icon whose ground IS the gold.
APPS = {
    "web": (NAVY, CREAM, GOLD),      # guests — the marketplace
    "partner": (CREAM, NAVY, GOLD),  # hosts and providers — reversed
    "console": (GOLD, NAVY, CREAM),  # us — the ground is the accent
}


def icon(size: int, ground: str, ink: str, accent: str, maskable: bool = False) -> str:
    """
    Fit to width and centre vertically.

    The wordmark is 2.25:1, so fitting it into a square by height would leave a
    stamp floating in a lot of nothing. Maskable icons take a much larger pad
    and a full-bleed ground: Android crops them to whatever shape the launcher
    fancies, and only the middle 80% is guaranteed to survive.
    """
    pad = size * (0.26 if maskable else 0.16)
    scale = (size - 2 * pad) / VB_W
    tx = pad
    ty = (size - VB_H * scale) / 2
    ground_el = (
        f'<rect width="{size}" height="{size}" fill="{ground}"/>'
        if maskable
        else f'<rect width="{size}" height="{size}" rx="{round(size * 0.22)}" fill="{ground}"/>'
    )
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {size} {size}" width="{size}" height="{size}">
  <!-- Generated by scripts/build-icons.py from components/logo.tsx. Do not hand-edit. -->
  {ground_el}
  <g transform="translate({tx:.2f} {ty:.2f}) scale({scale:.4f})">
    <path d="{WORD}" fill="{ink}"/>
    <path d="{STOP}" fill="{accent}"/>
  </g>
</svg>
"""


for app, (ground, ink, accent) in APPS.items():
    out = ROOT / f"apps/{app}/public"
    if not out.is_dir():
        print(f"skipping {app}: no public/ directory", file=sys.stderr)
        continue
    for s in (192, 512):
        (out / f"icon-{s}.svg").write_text(icon(s, ground, ink, accent))
    (out / "icon-maskable.svg").write_text(icon(512, ground, ink, accent, maskable=True))
    print(f"{app}: icon-192.svg, icon-512.svg, icon-maskable.svg")
