#!/usr/bin/env python3
"""
Regenerate the PWA icons from the logo component, and check the mark has not
drifted between the three apps.

The icon and the in-app wordmark are the same mark; the only way to keep them
that way through a redesign is to build one from the other. Run this after any
change to components/logo.tsx:

    python3 scripts/build-icons.py

The marketplace, the partner console and the business console each ship their
own copy of the component — they are separate Next apps and `@ciao/shared` is
consumed by the API too, so it cannot hold JSX. Three copies of a logo is
exactly how a brand ends up with three logos, so this script fails loudly if
they stop being byte-identical rather than waiting for someone to notice a
different mark on partners.ciao.ly.
"""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

CANONICAL = ROOT / "apps/web/src/components/logo.tsx"
COPIES = [
    ROOT / "apps/partner/src/components/logo.tsx",
    ROOT / "apps/console/src/components/logo.tsx",
]
comp = CANONICAL.read_text()
drifted = [p for p in COPIES if p.read_text() != comp]
if drifted:
    for p in drifted:
        print(f"logo drift: {p.relative_to(ROOT)} differs from apps/web", file=sys.stderr)
    print("copy the marketplace component over them and re-run.", file=sys.stderr)
    raise SystemExit(1)

def const(name: str) -> str:
    """Pull a `const NAME = {...}` object literal's body out of the component."""
    return re.search(rf"const {name} = {{(.+?)}};", comp, re.S).group(1)


def num(body: str, key: str) -> float:
    return float(re.search(rf"\b{key}:\s*(-?[\d.]+)", body).group(1))


LETTERS = re.search(r'const LETTERS =\n  "(.+?)";', comp, re.S).group(1)
_dot, _stop, _vb = const("I_DOT"), const("STOP"), const("VB")
D = {k: num(_dot, k) for k in "xywh"}
S = {k: num(_stop, k) for k in "xywh"}
VB = {k: num(_vb, k) for k in "xywh"}


def icon(size: int) -> str:
    pad = size * 0.14
    scale = (size - 2 * pad) / VB["w"]
    tx = pad - VB["x"] * scale
    ty = (size - VB["h"] * scale) / 2 - VB["y"] * scale
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {size} {size}" width="{size}" height="{size}">
  <!-- Generated by scripts/build-icons.py from components/logo.tsx. Do not hand-edit. -->
  <rect width="{size}" height="{size}" rx="{round(size * 0.22)}" fill="#0d1b2a"/>
  <g transform="translate({tx:.2f} {ty:.2f}) scale({scale:.4f})">
    <g fill="#f5eedd">
      <path d="{LETTERS}"/>
      <rect x="{D['x']:g}" y="{D['y']:g}" width="{D['w']:g}" height="{D['h']:g}"/>
    </g>
    <rect x="{S['x']:g}" y="{S['y']:g}" width="{S['w']:g}" height="{S['h']:g}" fill="#e8a020"/>
  </g>
</svg>
'''


for s in (192, 512):
    (ROOT / f"apps/web/public/icon-{s}.svg").write_text(icon(s))
    print(f"wrote icon-{s}.svg")
