#!/usr/bin/env python3
"""
Regenerate the PWA icons from the logo component, and check the mark has not
drifted between the three apps.

The icon and the in-app wordmark are the same mark; the only way to keep them
that way through a redesign is to build one from the other. Run this after any
change to components/logo.tsx:

    python3 scripts/build-icons.py

The marketplace, the partner console and the business console each ship their
own copy of the component — they are separate Next apps and `@ciao/shared` is
consumed by the API too, so it cannot hold JSX. Three copies of a logo is
exactly how a brand ends up with three logos, so this script fails loudly if
they stop being byte-identical rather than waiting for someone to notice a
different mark on partners.ciao.ly.
"""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

CANONICAL = ROOT / "apps/web/src/components/logo.tsx"
COPIES = [
    ROOT / "apps/partner/src/components/logo.tsx",
    ROOT / "apps/console/src/components/logo.tsx",
]
comp = CANONICAL.read_text()
drifted = [p for p in COPIES if p.read_text() != comp]
if drifted:
    for p in drifted:
        print(f"logo drift: {p.relative_to(ROOT)} differs from apps/web", file=sys.stderr)
    print("copy the marketplace component over them and re-run.", file=sys.stderr)
    raise SystemExit(1)

CIA = re.search(r'const CIA_PATH =\n  "(.+?)";', comp, re.S).group(1)
VB = (-48, -76, 250, 82)


def icon(size: int) -> str:
    vb_x, vb_y, vb_w, vb_h = VB
    pad = size * 0.14
    scale = (size - 2 * pad) / vb_w
    tx = pad - vb_x * scale
    ty = (size - vb_h * scale) / 2 - vb_y * scale
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {size} {size}" width="{size}" height="{size}">
  <!-- Generated by scripts/build-icons.py from components/logo.tsx. Do not hand-edit. -->
  <rect width="{size}" height="{size}" rx="{round(size * 0.22)}" fill="#0d1b2a"/>
  <g transform="translate({tx:.2f} {ty:.2f}) scale({scale:.4f})">
    <g fill="#f5eedd">
      <path d="{CIA}"/>
      <circle cx="160.78" cy="-24.25" r="17.88" fill="none" stroke="#f5eedd" stroke-width="11.8"/>
      <rect x="53.2" y="-71.9" width="19.6" height="19.6"/>
    </g>
    <rect x="-31" y="-19.6" width="19.6" height="19.6" fill="#e8a020"/>
  </g>
</svg>
'''


for s in (192, 512):
    (ROOT / f"apps/web/public/icon-{s}.svg").write_text(icon(s))
    print(f"wrote icon-{s}.svg")
